name: notebooks-cpu-2020-02
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pytorch
  - scikit-learn
  - scipy
  - jupyterlab
  - pandas
  - tqdm
  - seaborn
  - requests
  - pillow
  - h5py
  - graphviz
  - matplotlib
  - nltk
  - sqlite
  - spyder
  - pytest
  - cython
  - gensim
  - xlwt
  - openpyxl
  - pydot
  - dask
  - pyyaml
  - py-xgboost
  - pytables
  - netcdf4
  - cupti
  - torchvision
  - torchtext
  - conda-forge::dask-jobqueue
  - conda-forge::librosa
  - conda-forge::sox
  - conda-forge::tensorboardx
  - pip
  - pip:
    - regex
    - transformers
    - visdom
    - tensorflow
    - onnxruntime
