name: notebooks
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.3.0
  - magma-cuda100
  - scikit-learn
  - scipy
  - jupyterlab
  - pandas
  - tqdm
  - seaborn
  - requests
  - pillow
  - h5py
  - graphviz
  - matplotlib
  - nltk
  - sqlite
  - spyder
  - pytest
  - cython
  - gensim
  - xlwt
  - openpyxl
  - pydot
  - dask
  - pyyaml
  - py-xgboost
  - pytables
  - netcdf4
  - cudatoolkit
  - cudnn
  - cupti
  - torchvision
  - torchtext
  - conda-forge::dask-jobqueue
  - conda-forge::librosa
  - conda-forge::sox
  - conda-forge::tensorboardx
  - pip
  - pip:
    - regex
    - transformers
    - visdom
    - tensorflow-gpu==2.0.0
